name: Github Pages Astro CI

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  pull_request:

  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install, build, and upload your site
        uses: withastro/action@v0
      - name: Deploy to GitHub Pages
        run: |
          yarn
          yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: preview
          path: dist/
      - run: |
          sudo apt install jq
          id=$(polinetworkpr.github.io/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)
          echo $id
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Find the preview [here](polinetworkpr.github.io/$id)'
          })
